### ISSUE TITLE
Doesn't honor minimize/maximize buttons being enabled in GNOME

### ISSUE THREAD

**Issue by ChristianWSmith** [tkashkin/Adwaita-for-Steam#100] opened 2023-01-22 15:00 UTC
Steps to reproduce:

1. Open gnome-tweaks -> Window Titlebars -> Maximize ✔ / Minimize ✔
2. Install Adwaita-for-Steam, restart Steam, apply Adwaita-for-Steam, restart Steam again
3. No maximize/minimize buttons on steam interface.

**Comment by tkashkin** [comment] 2023-01-22 15:54
Duplicate of #13.

Steam does not use this option and the skin has no way to know how your system is configured.

There are a few window control presets, install the skin with the [installer script](https://github.com/tkashkin/Adwaita-for-Steam#installation) or the [graphical installer app](https://github.com/Foldex/AdwSteamGtk) to use them.

**Closed by tkashkin** 2023-01-22 15:54 UTC
