### ISSUE TITLE
Issues with the window controls patches on the new UI

### ISSUE THREAD

**Issue by D3SOX** [tkashkin/Adwaita-for-Steam#152] opened 2023-06-16 15:45 UTC
They are broken on the friend window
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/24937357/0a58ec75-e813-4151-9ab1-676b2fb73f74)

And not applied on settings (not sure if they were before)
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/24937357/1685910d-18f9-4802-90aa-4f41a12baa8b)

Used install parameters: `./install.py -we windowcontrols/left-all -c catppuccin-mocha -we library/hide_whats_new`

**Comment by Foldex** [comment] 2023-06-17 02:27
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/a3e90736-0cf6-4b35-b87e-7cc348a5240b)

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/1ab6f5f1-74a7-45d6-a337-19936c253a9f)

Couldn't reproduce the first one. Are you on the beta or stable?
On a hunch here, but try deleting your `steamui` folder, relaunching steam to regenerate it, then reinstalling.

Second one should be fixed though.
The overlay should also now be affected by this web extra, with small caveats:

- The Notes Dialog is quite different from other overlay dialogs, so I had to leave the pin/cloud sync buttons on the right.
- Left-All Extra pads the Friends Avatar so that the window controls can fit without overlap, but Minimize/Maximize don't exist in the overlay. The result is a bit weird looking, but I don't see a way to correct this as the embedded friends list is the same as the normal one.

![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/7bf5bbe3-5e6b-411c-ae16-f4e2308ac7eb)
![image](https://github.com/tkashkin/Adwaita-for-Steam/assets/47908676/e6859ccd-034c-4053-88ac-53d8f2a15f45)

**Closed** 2023-06-17 11:23 UTC

**Comment by D3SOX** [comment] 2023-06-17 11:43
I'm on the beta, but your PR also fixed the friends window for me so everything is resolved here 😃
