### ISSUE TITLE
Titlebar Buttons For Popup Windows Do Not Follow Left-Aligned Selection

### ISSUE THREAD

**Issue by cprin21** [tkashkin/Adwaita-for-Steam#85] opened 2022-12-11 02:40 UTC
As the title says, selecting left-aligned, whether full or just the close button, on windows like Friend List and Chat, the titlebar buttons are on the right. See #84 for an image example.

**Comment by Foldex** [comment] 2022-12-28 01:11
Duplicate of https://github.com/tkashkin/Adwaita-for-Steam/issues/56

**Closed** 2023-03-24 00:06 UTC
