### ISSUE TITLE
[Bug] Library UI not themed and not displaying correctly on fedora 37

### ISSUE THREAD

**Issue by ThatTakashi** [tkashkin/Adwaita-for-Steam#119] opened 2023-03-16 06:46 UTC
After todays steam update, the library UI of the launcher is no longer themed and is having issues displaying correctly. I will provide screenshots and system info below

![image](https://user-images.githubusercontent.com/45578020/225536277-5b8d5340-cb6d-4db1-a6f5-e0c5c3559f6d.png)

### System information:
- Intel core i7 6100U
- Intel integrated graphics 520
- 8gb of ram
- Fedora 37
- Gnome 43.3

**Comment by tkashkin** [comment] 2023-03-16 10:23
Duplicate of #113.

Nothing we can do now if Steam does not inject styles from `webkit.css` into web UI anymore.
This change was probably intentional to make the behavior more consistent on different platforms, because Windows builds of Steam never allowed to inject styles into the web UI at all.

Maybe something like [SFP](https://github.com/PhantomGamers/SFP) could work.

Or maybe Valve could add a supported way to override CSS for skins if they still want to support them, but thats very unlikely, considering that they seem to be slowly moving away from VGUI and the web UI is still not skinnable.
The most likely outcome I see is Steam eventually dropping the skin support entirely when they finish the transition from VGUI.

---

Display issues on your screenshot are likely a Steam bug. Is the window itself scrollable?
The library on your screenshot seems to be cut off at the top, so it may actually be scrolled inside the window.
The latest beta had a few similar bugs, some of them seem to be fixed, but maybe not all of them.

**Closed** 2023-03-19 21:47 UTC
