### ISSUE TITLE
The hover menu on the top right doesn't appear to work?

### ISSUE THREAD

**Issue by Kevadroz** [tkashkin/Adwaita-for-Steam#235] opened 2024-03-19 14:11 UTC
[bugged_mouse_hover.webm](https://github.com/tkashkin/Adwaita-for-Steam/assets/16049149/8cf18815-0bbd-4ffb-8e2a-66ce74e4f5a8)

(Don't mind that line in the middle, it's a recording artifact)

So when I move my mouse pointer over the hover menu it disappears, I have the theme installed via CSS Loader along some other tweaks, but this started happening out of nowhere one or two months ago, I haven't changed my desktop themes since.

**Comment by queenbiscuit311** [comment] 2024-03-20 04:29
it seems that this randomly breaks, as i recall this exact issue being present a while back. if its going to be unreliable then i really wish there was just an option to not have this hover menu and have the icons all present given that there is space for them

**Comment by tkashkin** [comment] 2024-03-20 07:38
Duplicate of #196. Menus seem to randomly break even in the regular Steam client without any customizations. I think it's not related to the way this skin shows the menus on hover.

> if its going to be unreliable then i really wish there was just an option to not have this hover menu and have the icons all present given that there is space for them.

No, I just don't think there's enough space. Maybe on very large window sizes, but still there will be like 10 buttons (+ window controls) on the right side and 3-4 buttons on the left side. There's already too many buttons there.

> either that or put these in the hamburger menu

I wanted to do that, but it seems there's no way to modify menu entries without patching Steam's JS code. Right now everything the skin does is CSS only. See #179 and #181.

**Closed by tkashkin** 2024-03-20 07:38 UTC

**Comment by queenbiscuit311** [comment] 2024-03-20 07:39
> Duplicate of #196. Menus seem to randomly break even in the regular Steam client without any customizations. I think it's not related to the way this skin shows the menus on hover.
> 
> > if its going to be unreliable then i really wish there was just an option to not have this hover menu and have the icons all present given that there is space for them.
> 
> No, I just don't think there's enough space. Maybe on very large window sizes, but still there will be like 10 buttons (+ window controls) on the right side and 3-4 buttons on the left side. There's already too many buttons there.
> 
> > either that or put these in the hamburger menu
> 
> I wanted to do that, but it seems there's no way to modify menu entries without patching Steam's JS code. Right now everything the skin does is CSS only. See #179 and #181.

Ah, I see
