### ISSUE TITLE
Clicking on screenshot in Library softlocks it.

### ISSUE THREAD

**Issue by Duckrinium** [tkashkin/Adwaita-for-Steam#137] opened 2023-04-04 14:48 UTC
I hope video explains it, if not, I'm happy to elaborate. 
It seems that some screenshots show fine, some don't, but closing it is softlocking Library every time.
Doesn't happen if you open screenshots window instead of clicking on screenshots themselves.

https://user-images.githubusercontent.com/37019004/229828939-4e11f62c-5ba6-4940-81e7-fe9692b123e2.mp4

_P.s. I'm actually very thankful for that restart Steam button!_

**Comment by Foldex** [comment] 2023-04-04 23:54
This looks like it's probably a steam client bug, can you recreate it while using the default theme?
Screenshots are supposed to open a popup dialog window, but this is opening up the dialog inside the main view. Clicking close there is trying to close a popup window that doesn't exist, which is probably why it locks up the client.

Regardless, we don't really have any control over how the web based sections of steam actually function, just how elements are styled.
As a separate issue: While I can't recreate  this as the dialog properly works for me, it could use some better theming.

**Comment by tkashkin** [comment] 2023-04-05 00:40
I've seen a few reports of the same Steam bug affecting different dialogs, it's not caused by the skin.
This bug may already be fixed in the [latest beta](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3684547928704734445).

I'll open a separate issue to discuss the screnshot dialog styling.

**Closed by tkashkin** 2023-04-05 00:40 UTC

**Comment by Duckrinium** [comment] 2023-04-05 06:22
Thanks for suggesting!

I've updated to latest beta that you mentioned, it is fixed now. Sorry, I completely forgot to check how it goes on default skin!
