### ISSUE TITLE
Hardware Survey Issues

### ISSUE THREAD

**Issue by Teddy-Kun** [tkashkin/Adwaita-for-Steam#98] opened 2023-01-09 07:11 UTC
I can scroll up on my library to reveal the following issue. Sometimes it's front and center on application start.
Steam is installed via the multilib/steam from the Arch repos and the theme is installed via AdwSteamGtk, with all window controls on the right.

![20230109_08h09m08s_grim](https://user-images.githubusercontent.com/58993831/211256393-ce70be63-7888-40ca-b1b0-92b39b4be3a8.png)

**Comment by tkashkin** [comment] 2023-01-09 08:51
Duplicate of #95.

This also happens with the default skin in the latest Steam beta.
Valve is moving notifications like phone/email verification banners from VGUI to the web part of the client and apparently adds some new types of notifications, but it's not fully working yet.

**Closed by tkashkin** 2023-01-09 08:51 UTC
