### ISSUE TITLE
How i can fix this?

### ISSUE THREAD

**Issue by fedep4lpi** [tkashkin/Adwaita-for-Steam#121] opened 2023-03-20 12:17 UTC
![Screenshot from 2023-03-20 13-11-52](https://user-images.githubusercontent.com/120409576/226336636-f01fa172-d3f8-4fea-9b0f-3379c6dec44c.png)

**Comment by tkashkin** [comment] 2023-03-20 12:36
Duplicate of #45.
You probably don't have the required fonts installed, install non-variable Cantarell fonts.

**Closed** 2023-03-20 14:10 UTC
