### ISSUE TITLE
Disappearing text in settings

### ISSUE THREAD

**Issue by p0k33m0n** [tkashkin/Adwaita-for-Steam#107] opened 2023-02-03 08:35 UTC
Disappearing text in settings when move mouse, it appear when clicking mouse on text.

Video included: https://megawrzuta.pl/download/756f1f6534a98b5aa3a8472d30532478.html

**Comment by tkashkin** [comment] 2023-02-03 09:04
Is it on Windows? If so, that's a duplicate of #97.
I don't know why that happens, can try to figure out what's wrong in a few days.

**Comment by p0k33m0n** [comment] 2023-02-03 17:54
Yes, this is Windows 10.

**Comment by p0k33m0n** [comment] 2023-02-03 18:24
I send new video. This is interesting, that text start disappear when mouse is in different section. I didn't click any time, only move mouse.

https://megawrzuta.pl/download/47cc6633ed882cbbc459453f490424de.html

**Comment by zhouLife** [comment] 2023-02-16 18:10
Me too win11_22H2

**Comment by Foldex** [comment] 2023-04-02 23:57
> any progress with this?

![ill-tell-you](https://user-images.githubusercontent.com/47908676/229385936-96750cc1-ef10-4345-85fc-dafe9dfc794d.gif)

**Closed** 2023-06-17 11:16 UTC

**Comment by p0k33m0n** [comment] 2023-06-17 11:26
Thank you.
